[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dira"
version = "0.1.0"
description = ""
authors = ["DIRA Core"]
readme = "README.md"
packages = [{include = "dira"}]
